api:
  jwt:
    secret: secret
    expiration: 86400000
spring:
  application:
    name: vuttr-api
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    h2:
      console:
        enabled: true
        path: /h2-console
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 3000